import type { CognitiveRegion } from "@/types/ava-mind";

export const COGNITIVE_REGION_DEFS: Omit<CognitiveRegion, "nodeIds" | "majorNodeId">[] = [
  {
    id: "awareness",
    name: "awareness",
    displayName: "Awareness",
    description: "Sensory attention across the current moment, active surroundings, and incoming context.",
    center: [-0.72, 0.36, 0.44],
    radius: 0.68,
    activity: 0.78,
  },
  {
    id: "memory",
    name: "memory",
    displayName: "Memory",
    description: "Stored patterns, past events, recovered references, and long-running operational context.",
    center: [0.72, -0.2, -0.3],
    radius: 0.74,
    activity: 0.66,
  },
  {
    id: "reasoning",
    name: "reasoning",
    displayName: "Reasoning",
    description: "Structured inference, prioritization, validation, and decision shaping.",
    center: [0.1, 0.66, -0.16],
    radius: 0.72,
    activity: 0.86,
  },
  {
    id: "attention",
    name: "attention",
    displayName: "Attention",
    description: "The active spotlight that ranks what matters now against the rest of the signal field.",
    center: [-0.16, 0.0, 0.82],
    radius: 0.56,
    activity: 0.74,
  },
  {
    id: "timeline",
    name: "timeline",
    displayName: "Timeline",
    description: "Temporal ordering, deadlines, event traces, and near-future projection.",
    center: [-0.42, -0.62, -0.08],
    radius: 0.58,
    activity: 0.58,
  },
  {
    id: "world-model",
    name: "world-model",
    displayName: "World Model",
    description: "Ava's structured map of systems, people, entities, relationships, and operating state.",
    center: [0.38, 0.14, 0.62],
    radius: 0.66,
    activity: 0.72,
  },
  {
    id: "personal-context",
    name: "personal-context",
    displayName: "Personal Context",
    description: "Private preferences, routines, priorities, and Cody-specific context.",
    center: [-0.8, -0.08, -0.38],
    radius: 0.6,
    activity: 0.62,
  },
  {
    id: "business-systems",
    name: "business-systems",
    displayName: "Business Systems",
    description: "CHILL TECH operations, client systems, reports, automations, and revenue-facing signals.",
    center: [0.18, -0.72, 0.38],
    radius: 0.64,
    activity: 0.81,
  },
  {
    id: "home-systems",
    name: "home-systems",
    displayName: "Home Systems",
    description: "Connected home telemetry, environment state, sensors, and background domestic awareness.",
    center: [0.78, 0.32, 0.06],
    radius: 0.52,
    activity: 0.54,
  },
];
